### ISSUE TITLE
Font size change doesn't change in editor

### ISSUE THREAD

**Issue by AanFadhil** [Roslovets-Inc/strapi-plugin-ckeditor5#41]
I'm using Strapi v4, changing font size does not affect the font size in editor preview even though the change is correctly saved

**Comment by elena-rafailova** [comment]
I just found it - in the Wrapper styled component in the CKEditor/index.js - where there is revert font styling - I removed the span element from it because I saw that fontSize wraps the text in span element and font: revert makes it so it doesn't show. Maybe it needs a little bit more testing, but that is a quick fix  🤗

**Comment by roslovets** [comment]
Fixed in v2.1.1-rc.1
