### ISSUE TITLE
Plugin options and HtmlEmbed

### ISSUE THREAD

**Issue by PritamSangani** [Roslovets-Inc/strapi-plugin-ckeditor5#5]
Hello! Thanks for building this plugin! I was wondering if there was any way of disabling some of the buttons on the toolbar. I want to disable the image and media library button.

**Comment by roslovets** [comment]
Hi, thanks! I will examine how to add custom CKEditor configuration.

**Comment by delaudio** [comment]
I'm interested too. Id' like to add HtmlEmbed to the list of plugins. It would be great if we could add or remove buttons depending on needs.

**Comment by roslovets** [comment]
Unfortunately i'm stuck with custom configuration. The idea was to setup CKEditor via `config/plugins.js` but I can't find mechanism of reading this file from custom plugin. May be somebody will help.

**Comment by roslovets** [comment]
But if you want I can enable [HtmlEmbed](https://ckeditor.com/docs/ckeditor5/latest/features/html-embed.html) feature in my CKEditor build.
Seems like it's pretty tricky feature, it will be good if you describe what do you want from it. Or you can create a Pull Request.

**Comment by delaudio** [comment]
Hi @roslovets if you can add HtmlEmbed to your CKEditor build it would be great, in the meanwhile during this week I'll study how to add/remove buttons configuration. 

I'd like to have the possibility to override the editor plugins based on project needs. For example, for a project I could need images, for another one just simple text with basic formatting. 

I've been using Strapi for a week and I haven't understood fully its system of customization. I'm not really sure how to make the override in this case. Should be in extension/content-manager, in admin or in plugins folder? Since it's part of the built admin front-end. Thank you

**Comment by roslovets** [comment]
> Should be in extension/content-manager, in admin or in plugins folder?

Yep, thanks for pointing out. I am preparing new release with HtmlEmbed and customization features.

**Comment by sebastiangorski** [comment]
Hi there! I was about to post a new Issue asking for HtmlEmbed integration when I saw this one. Seems like the integrations is already happening, which is great news! 

I step upon your plugin @roslovets when I was researching an issue in strapi repo about CKEditor not working when Article has additional relational fileds (like Category, Author etc.). I'm not sure if you want to share the knowledge how did you managed to fix that issue, but it would be great to learn from your experience. 

Anyway, I'm also in desperate need to add HtmlEmbed in CKEditor, but since the regular CKEditor version is not working with strapi, adding any plugins to it is pointless. So here I am, reading you guys and wondering when the new version of this plugin containing HtmlEmbed integration will be available. :D 

As I understand there is no way to add additional plugins to your version of CKEditor as for now?

**Comment by roslovets** [comment]
Hi! HtmlEmbed is on the way)

I created this plugin to fix blank editor content in Strapi v3.4.1. I've just added a proper CKEditor initialization:

https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5/blob/0532f3b87ac98dd393715f0fd56cbef1320d6b88/admin/src/components/CKEditor/index.js#L44

```js
onReady={editor => {
  if (value) {
    editor.setData(value);
  }
}}
``` 

If you want to add any plugin to CKEditor yourself you have to create your own CKEditor build and your own Strapi plugin based on your build. This is so much routine that I decided to create one comprehensive plugin for a wide variety of uses.

That's why I collect your requests to integrate useful features to my [enhanced build](https://github.com/Roslovets-Inc/ckeditor5-build-strapi-wysiwyg).

**Comment by roslovets** [comment]
Check out HtmlEmbed and editor customization in [v1.4.0](https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5/releases/tag/v1.4.0)!

**Comment by sebastiangorski** [comment]
@roslovets great work, well done! I just updated my project with the newest version of your plugin. HtmlEmbed works like a charm. :) Thank you very much!
